### ISSUE TITLE
Few issues in RR 20170219 build

### ISSUE THREAD

**Issue by max20091** [latte-dev/android_device_xiaomi_latte#1]
Sleep bug (turn off the screen for a while then cannot turn it on anymore, it's looks like the tablet shut down itself)
Some GApps zip not work (some copied to priv-app but not install and some didn't appear in app or priv-app)
Controlling screen bightness and captivate button brightness seems not working ( can't control the values in /sys/class)
Audio worked but can't increase or decrease using vol up and vol down button (same bug above)
Storage space show wrong number (should be 12GB instead of 16GB)
Graphic glitch when I change wallpaper using gallery and the launcher crashed if I use a high-res png (30 MB image maybe)
Touch buttons not work (fix available in https://github.com/latte-dev/android_vendor_xiaomi_latte/issues/2)

**Comment by tank0412** [comment]
Heklo.
In 20170227 build opengapps, brightness, buttons, audio changing was fixed.

**Comment by harrynowl** [comment]
As the issues are resolved, I'll close this issue.
