### ISSUE TITLE
Incorrect battery percentage bug?

### ISSUE THREAD

**Issue by max20091** [latte-dev/android_device_xiaomi_latte#5]
I ran my tablet until the OS say shutting down then I leave TWRP running 8 more hours before the tablet truly can't turning on anymore.
Is this a battery bug or something?
Anyway, Mi Pad 2 have 6190 mAh, why the readme say 6020 mAh?

**Comment by harrynowl** [comment]
The battery is rated at 6020mAH minimum (or 6010 looking at some pictures) and 6190 typical. Battery profile used by Xiaomi's implementation of the battery platform is here: https://github.com/latte-dev/android_kernel_xiaomi_latte/blob/cm-13.0/drivers/platform/x86/intel_em_config.c#L75

**Comment by tank0412** [comment]
Android uses digits from this power profile, which was taken from stock MIUI rom.
https://github.com/latte-dev/android_device_xiaomi_latte/blob/cm-13.0/overlay/frameworks/base/core/res/res/xml/power_profile.xml#L71
So all is OK i think
