### ISSUE TITLE
I think it is better use full_phone.mk to make rom

### ISSUE THREAD

**Issue by lly-q** [latte-dev/android_device_xiaomi_latte#7]
Android compatibility declined, there have been many applications dislocation。But xposed can be installed.Dpi is a promble.

**Comment by tank0412** [comment]
I do not think so.
Xposed can be installed any way.
And this tablet does not have a SIM card slot so it does not needed.

**Comment by lly-q** [comment]
I had try to make it now.No error about telephoney
