### ISSUE TITLE
Current state of this project

### ISSUE THREAD

**Issue by Flole998** [latte-dev/android_device_xiaomi_latte#9]
Hi @tank0412 and @harrynowl,

I've recently starting to find new use-cases for my old MiPad 2 and in doing so I've found this ROM. I've found some bugs, some of which I already fixed by editing the boot.img or system partition. Are you open to picking this project up again and accepting and merging new PRs or do you no longer plan to actively work on this project?

I've also written a small binary which forces the device to charge in OTG mode (needs an appropriate adapter of course).

Let me know if there's any chance to bring this back to life or if I'm pretty much on my own right now. I've seen that there was some work on Android N, but seems like it unfortunately stalled.

**Comment by tank0412** [comment]
Hi! Unfortunately, I do not have a Mi Pad 2 anymore. So development is stopped.
